### ISSUE TITLE
Update for .NET 6, Url Endpoints?

### ISSUE THREAD

**Issue by TimPurdum** [mdisibio/tempo-otel-dotnet-example#1]
@mdisibio I was trying to follow your excellent blog post attached to this repo, but using the latest version of the nuget packages. Unfortunately, there have been some breaking changes. Most notably, the line `opt.Endpoint = "grafana-agent:55680";` no longer works, as this property was changed to a `Url`, and only accepts http/https addresses. I have tried tinkering around with replacing that on my own, but have been unable to get my Asp.NET app to connect to my grafana agent.

Connections I have tried:
`http://localhost:55680`
`http://localhost:4317` (got that by trying to read the agent startup log)

My app does hit the Console Exporter, so I know that much is working.

`WebApplication1.csproj`
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.3.1" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.3.1" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9.6" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.6" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
    </ItemGroup>

</Project>
```

`docker-compose.yaml`
```yaml
version: "3"
services:

 app:
   image: mcr.microsoft.com/dotnet/sdk:6.0
   command: bash -c "dotnet restore && dotnet build && dotnet run  --urls http://+:5000"
   working_dir: /WebApplication1
   volumes:
     - ./WebApplication1:/WebApplication1
   ports:
     - "5000:5000"

 grafana-agent:
   image: grafana/agent:latest
   command: "-config.file=/etc/agent-config.yaml"
   volumes:
     - ./agent-config.yaml:/etc/agent-config.yaml
 ```

`agent-config.yaml`
```yaml
traces:
  configs:
  - name: default
    remote_write:
      - endpoint: tempo-us-central1.grafana.net:443
        basic_auth:
          username: <my username>
          password: <my password>
    receivers:
      otlp:
        protocols:
          grpc:
```
